# pods的endpoints默认在创建service时创建
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: ##appName##
  name: ##appName##
  namespace: ##appNamespace##
subsets:
- addresses:
  - ip: # 默认会自动获取
    nodeName: # 默认会自动获取Pod所在的NodeName
    targetRef:
      kind: Pod
      name: ##appPodName##
      namespace: ##appNamespace##
  ports:
  - name: http   # 最好同步PodsPortHttpName
    port: 80     # Pod暴露的http端口
    protocol: TCP
  - name: tcp    # 最好同步PodsPortTcpName
    port: 80     # Pod暴露的tcp端口
    protocol: TCP

---
# 外部的服务，在k8s上暴露到外网
apiVersion: v1
kind: Endpoints
metadata:
  name: ##externalServerName##
  namespace: ##Namespace##
  labels:
    app: ##externalServerName##
subsets:
- addresses:
  - ip: ##externalServerIp##
  ports:
  - name: http  # 自定义
    port: 8080  # 外部服务的端口，需要确保k8s能正常请求
    protocol: TCP # 暴露的协议，支持TCP/UDP，首选TCP