# Dockercfg
apiVersion: v1
data:
  .dockercfg: ##authorizedToken##  # base64加密，加密前的格式：base64({"<url>":{"username":"<username>","password":"<password>","auth":"base64(<username:password>)"}})
kind: Secret
metadata:
  name: ##authName##
  namespace: ##authNamespace##
type: kubernetes.io/dockercfg

---
# TLS
apiVersion: v1
data:
  tls.crt: ##base64(tlsCrt)##
  tls.key: ##base64(tlsKey)##
kind: Secret
metadata:
  name: ##TLSName##
  namespace: ##TLSNamespace##
type: kubernetes.io/tls

---
# Opaque
apiVersion: v1
data:
  # 内容文件可以多个，挂载到Pod上时恢复明文的
  file1.txt: ##base64(data)##
  file2.txt: ##base64(data)##
  file3.txt: ##base64(data)##
  file4.txt: ##base64(data)##
kind: Secret
metadata:
  name: ##secretName##
  namespace: ##secretNamespace##
type: Opaque
